dist: bionic
language: cpp
compiler:
- gcc
addons:
  apt:
    packages:
    - qt5-default
    - g++-11-multilib
    - gcc-11-multilib
    - linux-libc-dev:i386
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test
install:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 20
before_script:
- mkdir build
- cd build
- qmake ../TFTrue.pro -r -spec linux-g++
script: make
after_success:
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- cp TFTrue.so ../release/TFTrue.so
- git add ../release/TFTrue.so
- git commit --message "Travis build $TRAVIS_BUILD_NUMBER"
- git remote add origin-public https://${GH_TOKEN}@github.com/AnAkkk/TFTrue.git > /dev/null 2>&1
- git push --quiet -u origin-public public
env:
  global:
    secure: DaTFgEEz8+E5ztX7aZ0vXozY2pVLd8UjiVSR9WPp87EIg2M5+z51mmlFL+DsFIEkJMt3As3rezL60Hg6hfgJoCwJzdrd3NYSCqFoKYT9enisiYC6x12cp2qz6od29HwQWFNwyem0FyQrb3aPBS+OZ6kjnk4WGMtUkhMdCsSgMcc=
