dist: focal
language: cpp

compiler:
  - clang
  - gcc
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get dist-upgrade -y
  - sudo apt-get -y install qt5-default g++-9-multilib linux-libc-dev:i386

before_script:
 - if [ $CXX == "clang++" ]; then qmake TFTrue.pro -r -spec linux-clang; fi
 - if [ $CXX == "g++" ]; then qmake TFTrue.pro -r -spec linux-g++; fi

script: make
