dist: bionic
language: cpp

compiler:
 - gcc

addons:
  apt:
    packages:
      - qt5-default
      - g++-11-multilib
      - gcc-11-multilib
      - linux-libc-dev:i386
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      
install:
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 20

before_script:
 - mkdir build
 - cd build
 - qmake ../TFTrue.pro -r -spec linux-g++

script: make
