sudo: required
dist: bionic
language: cpp

compiler:
  - clang
  - gcc
  
addons:
  apt:
    packages:
      - g++-multilib
      - gcc-multilib
      - clang

before_script:
 - wget https://github.com/AnAkIn1/source-sdk-2013/archive/master.zip
 - unzip -qq master.zip
 - sed -i '/SOURCE_DIR =/c\SOURCE_DIR=$$PWD/source-sdk-2013-master/mp/src' TFTrue.pro
 - if [ $CXX == "clang++" ]; then qmake TFTrue.pro -r -spec linux-clang; fi
 - if [ $CXX == "clang++" ]; then sed -i 's/= clang++$/= clang++-3.7/g' Makefile; fi
 - if [ $CXX == "clang++" ]; then sed -i 's/= clang$/= clang-3.7/g' Makefile; fi
 - if [ $CXX == "g++" ]; then qmake TFTrue.pro -r -spec linux-g++; fi

script: make
