os: linux

dist: bionic

language: cpp

compiler:
- gcc

addons:
  apt:
    packages:
    - g++-11-multilib
    - gcc-11-multilib
    - linux-libc-dev:i386
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test
    - sourceline: 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ bionic main'
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'

install:
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 20
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 20
before_script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --verbose

script: make

after_success:
# set up our cfg
- git config --global user.email "travis@travis-ci.com"
- git config --global user.name "Travis CI"
# copy our just built file to the releases folder
- cp ./TFTrue.so ../release/TFTrue.so -vf
# checkout our current branch, so we're not on a detatched head
- git checkout ${TRAVIS_BRANCH}
# add our built file
- git add ../release/TFTrue.so
# commit, add correct remote, and push
- git commit --message "Travis build ${TRAVIS_BUILD_NUMBER} on branch ${TRAVIS_BRANCH}"
- git remote add origin-push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
- git push -u origin-push ${TRAVIS_BRANCH}

# GH_TOKEN is a secret token defined in your travis proj

