language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

before_script:
 - wget https://github.com/ValveSoftware/source-sdk-2013/archive/master.zip
 - unzip master.zip
 - export SOURCE_SDK = $PWD/source-sdk-2013-master/mp/src
 - sed -i '/SOURCE_DIR/c\SOURCE_DIR=$$SOURCE_SDK' TFTrue.pro

script:
 - qmake -project
 - qmake TFTrue.pro
 - make
