dist: focal
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - qt5-default
      - g++-multilib
      - gcc-multilib
      - g++-9-multilib
      - gcc-9-multilib
      - linux-libc-dev:i386

before_script:
 - if [ $CXX == "clang++" ]; then qmake TFTrue.pro -r -spec linux-clang; fi
 - if [ $CXX == "g++" ]; then qmake TFTrue.pro -r -spec linux-g++; fi

script: make
