dist: bionic
language: cpp

addons:
  apt:
    packages:
      - qt5-default
      - g++-11-multilib
      - gcc-11-multilib
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      
jobs:
  include:
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-11
        - CXX=g++-11
        
before_script:
 - qmake TFTrue.pro -r -spec linux-g++

script: make
