dist: bionic
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - qt5-default
      - g++-11-multilib
      - gcc-11-multilib
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'

before_script:
 - if [ $CXX == "clang++" ]; then qmake TFTrue.pro -r -spec linux-clang; fi
 - if [ $CXX == "g++" ]; then qmake TFTrue.pro -r -spec linux-g++; fi

script: make
