dist: focal
language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo apt --fix-broken install
 - sudo aptitude install g++-9-multilib gcc-9-multilib qt5-default

before_script:
 - if [ $CXX == "clang++" ]; then qmake TFTrue.pro -r -spec linux-clang; fi
 - if [ $CXX == "g++" ]; then qmake TFTrue.pro -r -spec linux-g++; fi

script: make
