language: cpp

compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

before_script:
 - wget https://github.com/ValveSoftware/source-sdk-2013/archive/master.zip
 - unzip master.zip
 - sed -i '/SOURCE_DIR/c\SOURCE_DIR=$$PWD/source-sdk-2013-master/mp/src' TFTrue.pro

script:
 - if [[ $COMPILER == 'clang' ]]; then qmake TFTrue.pro -r -spec linux-clang
 - if [[ $COMPILER == 'gcc' ]]; then qmake TFTrue.pro -r -spec linux-g++
 - make
